### ISSUE TITLE
compiling in ubuntu

### ISSUE THREAD

**Issue by yodog** [kvic-z/pixelserv-tls#1]
what do i have to change to get it to compile on ubuntu 16?
currently i'm using nginx serving a 1px gif, but it doesn't work for tls connections.

**Comment by MrT69** [comment]
1. Let's assume you create a directory "**/opt/devel**". Extract to this folder the entire Source Code.

2. Now change to /opt/devel/openssl/amd64 and create there 2 symbolic links.
libcrypto.a from /usr/lib/x86_64-linux-gnu/libcrypto.a
libssl.a from /usr/lib/x86_64-linux-gnu/libssl.a

3. Take a look at the Source Code and find this:
**pixelserv.c** >>> folderr = "/opt/var/cache/pixelserv";
**util.h** >>> #define DEFAULT_PEM_PATH "/opt/var/cache/pixelserv"
Change this folder or create this and copy there your ca.crt and ca.key.

4. Go back to **/opt/devel** where you should now have the source code and type "**make amd64**"

5. The compiler runs with a few errors but the binary will be compiled.

6. Now you can use the compiled binary. If the ca.crt and ca.key is missing it will not start

**Comment by yodog** [comment]
perfect! 
thank you for your time.
