### ISSUE TITLE
Not included in "ENTWARE"-----Unknown package !

### ISSUE THREAD

**Issue by jenom1957** [kvic-z/pixelserv-tls#14]
root@unknown:/# opkg install pixelserv-tls
Unknown package 'pixelserv-tls'.
Collected errors:
 * opkg_install_cmd: Cannot install package pixelserv-tls.

**Comment by kvic-z** [comment]
I guess your Entware installation might be terribly outdated? Try updating Entware package db first.
```
$ opkg update
$ opkg install pixelserv-tls
```

**Comment by kvic-z** [comment]
Close issue due to inactivity.
v2.1.1 is also available from Entware.
