### ISSUE TITLE
TEMP_FAILURE_RETRY missing from musl

### ISSUE THREAD

**Issue by laoshaw** [kvic-z/pixelserv-tls#2]
TEMP_FAILURE_RETRY is glibc only, so it failed to build on openwrt-lede, where musl is now the default library, maybe you can add the workaround at:

https://github.com/flatpak/flatpak/issues/618

**Comment by kvic-z** [comment]
Added [10c4351](https://github.com/kvic-z/pixelserv-tls/commit/10c435133b96940f2462345acbbcc53baf18ae09?diff=unified). 

Thanks for notifying me.
