### ISSUE TITLE
Compiling issues in homebrew/macos

### ISSUE THREAD

**Issue by jrmwvu04** [kvic-z/pixelserv-tls#23]
Some problems I've come across, and a brief mention on how I've worked around so far. The result is a running, but incorrectly, binary. pixelserv-tls will run and the web UI is responsive, but crashes upon any external connection with abort trap: 6 (SIGABRT as I understand it).

ISSUE 1
Error: `<linux/version.h>` in `pixelserv.c` and `util.h`
(Removed with no replacement.)

ISSUE 2
Error: `<malloc.h>` in `pixelserv.c` and `certs.c`
(Changed to `<malloc/malloc.h>` - seems to be just a minor change to fix.)

ISSUE 3
Error: Incompatible `SOL_TCP` in `pixelserv.c`
(Change to `IPPROTO_TCP`)

ISSUE 4
Error: Incompatible `KERNEL_VERSION()` in `pixelserv.c` and `util.h`
(Removed with no replacement)

ISSUE 5
Error: Incompatible `SO_BINDTODEVICE` in `pixelserv.c`
(Change to `IP_RECVIF`)

ISSUE 6
Error: Incompatible `MSG_NOSIGNAL` in `socket_handler.c`
(Change to 0)

ISSUE 7
Error: Incompatible `--gc-sections` in `Makefile.in`
(Change to `-dead_strip`)

**Comment by kvic-z** [comment]
Thanks for documenting your findings in detail. They help in my porting to MacOS/Homebrew. Commit [0fdf1f5](https://github.com/kvic-z/pixelserv-tls/commit/0fdf1f529c733b7dd0b2bef4a023335497397492)
