### ISSUE TITLE
HTML Status Page

### ISSUE THREAD

**Issue by patrickemuller** [kvic-z/pixelserv-tls#24]
When I installed Diversion and enabled Pixeserv-TLS to run along it, I was able to view the `/servstats` page. But after a few days this page stop working for me.
Can't load any page `/servstats` or `/servstats.txt`.

Also, would be nice to have some web GUI like PiHole does, with a few infos about the "performance" of the Blocker and some basic configuration.

**Comment by decoderman** [comment]
> When I installed Diversion and enabled Pixeserv-TLS to run along it, I was able to view the `/servstats` page. But after a few days this page stop working for me.
> Can't load any page `/servstats` or `/servstats.txt`.
> 
> Also, would be nice to have some web GUI like PiHole does, with a few infos about the "performance" of the Blocker and some basic configuration.

In Diversion, enter ep and select to restart pixelserv-tls.
You may also want to check the Router Syslog for errors pertaining to pixelserv-tls.

As for a Diversion WebUI, this is the wrong place to bring this up. Diversion will not have a WebUI for some time. I only have limited resources to code and the WebUI is on the low priority list ATM.

**Comment by patrickemuller** [comment]
@decoderman thanks a lot, you already helped me! Gonna close this for now 😄
