### ISSUE TITLE
pixelserv-tls not interception

### ISSUE THREAD

**Issue by hyber-code** [kvic-z/pixelserv-tls#29]
I have the follwing setup.

I have pixelcerv-tls with pihole without web interface and pivpn installed on debian stretch 9. with all the clients connecting through vpn.

despite pixelserv-tls listening on port 80 and 443 with cert installed on windows and android device and pihole sending requests to 0.0.0.0 , pixelserv-tls is not intercepting, resulting in page not found for ads. does it has something to do with vpn settings or any other issue ?

````
xxxx@xxxx:~$ sudo su
xxxx@xxxx:/home/xxxx# netstat -ltnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:4711          0.0.0.0:*               LISTEN      2223/pihole-FTL     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2745/pixelserv-tls  
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      2223/pihole-FTL     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      862/sshd            
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      2745/pixelserv-tls  
tcp        0      0 0.0.0.0:444             0.0.0.0:*               LISTEN      604/openvpn         
tcp6       0      0 ::1:4711                :::*                    LISTEN      2223/pihole-FTL     
tcp6       0      0 :::53                   :::*                    LISTEN      2223/pihole-FTL     
tcp6       0      0 :::22                   :::*                    LISTEN      862/sshd 
````

setting in setupVars.conf
````
PIHOLE_INTERFACE=eth0
PIHOLE_INTERFACE=tun0
PIHOLE_INTERFACE=tun1
IPV4_ADDRESS=0.0.0.0
IPV6_ADDRESS=0.0.0.0
PIHOLE_DNS_1=10.128.0.1
#PIHOLE_DNS_2=8.8.4.4
QUERY_LOGGING=true
INSTALL_WEB_SERVER=false
INSTALL_WEB_INTERFACE=false
LIGHTTPD_ENABLED=false
BLOCKING_ENABLED=true
DNSMASQ_LISTENING=all

````
follwing is settings in pihole-FTL.conf

````
PRIVACYLEVEL=0
BLOCKINGMODE=IP-NODATA-AAAA

````

sample output from pihole -t

````
dnsmasq[2223]: query[A] ssl.google-analytics.com from 10.8.0.3
dnsmasq[2223]: /etc/pihole/gravity.list ssl.google-analytics.com is 0.0.0.0

````

follwing is the screeshot of servstats

![pixelserv](https://user-images.githubusercontent.com/18413990/62009145-953a9080-b164-11e9-98a9-9311aac3c306.jpg)

Thank you very much for your help

**Comment by hyber-code** [comment]
Please let me know if you need any other data, have spet two days on figuring out what could be the issue but couldn't , i followed your guide to use pihole with pixelserv-tls and some guide to use pihole with pivpn 

Thank you for the excellent program.

**Comment by TorstenJahnke** [comment]
pixelserv must not listen on IP 0.0.0.0 
This is not an IP Adresse because it's a network address.

**Comment by hyber-code** [comment]
i have used other ip address also with same result like 10.128.0.6 in my case and simultaneously changinf the ip in pihole ipv4

**Comment by hyber-code** [comment]
or  can you please tell which ip i should based on following result 

````
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1460
        inet 10.128.0.6  netmask 255.255.255.255  broadcast 10.128.0.6
        inet6 fe80::4001:aff:fe80:6  prefixlen 64  scopeid 0x20<link>
        ether 42:01:0a:80:00:06  txqueuelen 1000  (Ethernet)
        RX packets 3319  bytes 883009 (862.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2513  bytes 623072 (608.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 48  bytes 4659 (4.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 48  bytes 4659 (4.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.9.0.1  netmask 255.255.255.0  destination 10.9.0.1
        inet6 fe80::1ab:3b0c:547e:d869  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10  bytes 480 (480.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun1: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.8.0.1  netmask 255.255.255.0  destination 10.8.0.1
        inet6 fe80::111a:a7a7:5dd1:2df5  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11  bytes 528 (528.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

````

**Comment by TorstenJahnke** [comment]
The problem seems to be the VPN interface. As soon as you switch to a different interface the routing will not longer work.
You have on each interface a /24 network. Without setting static routes on your router you are not able to access the other networks. In addition you are using the VPN which make it almost impossible to access this.

Because of this fact I have invented the keweon project and this is working with public IP addresses. Because of this you can always access the "pixelserver". :-)

**Comment by hyber-code** [comment]
I am on a debian stretch 9 with static public address. so what should i do fix this ? thank you very much in advance

**Comment by TorstenJahnke** [comment]
Just use my DNS Servers. If you want to know more then ask Google or XDA.

1. 213.239.207.143 and 107.191.55.215

2. Get the Root Cerificate from:
https://pki.keweon.center

3. DNS over HTTPS and DNS over TLS Server
DoT address: dot.asecdns.com
DoH address: https://doh.asecdns.com/nebulo

4. The public "pixelserver" is adblock.keweon.center with IP address 5.189.169.177

Almost the entire systems are located within Germany.

Current blacklist Database contains 56 Million entries

Have fun 😉

**Comment by hyber-code** [comment]
i am interested in solution specific to my setup.

**Comment by TorstenJahnke** [comment]
That's too much routing efforts and on the other hand I have seriously no clue about your VPN and required settings. To do this via a chat is almost not possible. Sorry...
