### ISSUE TITLE
ipks for 2.3.1

### ISSUE THREAD

**Issue by jackyaz** [kvic-z/pixelserv-tls#34]
hi, can you provide me with the ipks so I can add to my fork as a short-term fix for asuswrt users to auto update please?

**Comment by kvic-z** [comment]
Hi jackyaz

Entware has their update schedule. In my opinion, it's worth waiting to pay them the respect. For the eager early birds, I provided a way in my [blog post](https://kazoo.ga/pixelserv-tls/) on how to get it updated. That's what I could do to make some ppl happy.

My build environment was not setup to release Entware packages. I don't intent to change it. Apparently I also can't prevent others from leapfrogging Entware release.  Anyhow that's how far I could go on this matter.

Cheers

**Comment by decoderman** [comment]
I'm with @kvic-z on this matter. The Entware maintainers will provide the updated version in due time. No need to hurry as @jackyaz unofficial version works just fine until then.

**Comment by jackyaz** [comment]
This drove my concern, from your blog:

> Caution: For users running the unofficial 'v2.3.0' patch to support Apple software, you're recommended to upgrade to v2.3.1 because I see a memory leakage in the patch that will de-stabilize your routers/servers.

**Comment by jackyaz** [comment]
If there is a serious memory leak, then I have the build environments ready to go, and have merged your commits into my fork.

I'll await further advice before firing off the builds.

**Comment by decoderman** [comment]
Entware is updated about once a month and currently overdue for an update. pixelserv-tls v2.3.0 is out since August and running fine AFAIK. I'd rather you build and host the mipsel v2.3.1 ipk so I can offer it to those users in Diversion.
