### ISSUE TITLE
deprecated openssl api usage

### ISSUE THREAD

**Issue by laoshaw** [kvic-z/pixelserv-tls#38]
at the moment pixelserv-tls requires old openssl API, will be it updated sometime?

for example: SSL_library_init, CRYPTO_THREADID etc.

**Comment by laoshaw** [comment]
https://www.wolfssl.com/docs/wolfssl-manual/ch13/  actually it might be even better to support wolfssl, wolfssl has openssl api but just 1/20 in size.

**Comment by kvic-z** [comment]
In what sense, the API's you pointed out are old? I didn't get deprecation notice as of OpenSSL 3.0.0-beta1.

I agree OpenSSL is becoming a bit FAT (especially on larger systems) for the purpose of pixelserv-tls. The beginning of pixelserv-tls was the other way round. I wanted to look at the OpenSSL API's and pixelserv-tls was a vehicle for that purpose.

If I decide to try new ideas like rewriting for http3 in future, I may consider wolfssl.
