### ISSUE TITLE
Not serving ca.crt

### ISSUE THREAD

**Issue by hyber-code** [kvic-z/pixelserv-tls#41]
Pixelserve is not serving ca.crt ( screenshot attached)

I am using pixelserv in a docker container on ubuntu on google cloud instance , followed all the steps, its is serving servstats though.

![Screenshot 2020-09-30 111212](https://user-images.githubusercontent.com/18413990/94654469-8b875c80-0316-11eb-825a-8a8d09f2a2c2.png)
![Screenshot 2020-09-30 111245](https://user-images.githubusercontent.com/18413990/94654480-8d512000-0316-11eb-94a4-bd8faad4171b.png)

**Comment by TorstenJahnke** [comment]
This would be a security risk if pixelserv provides the Certificate within this way.
What exactly you want to do?

**Comment by hyber-code** [comment]
Solved: ca.crt generated through this guide ``` https://hub.docker.com/r/imthai/pixelserv-tls ``` were not generated in the pixelserv folder, i moved them inside the folder and its is working perfecly.
