### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by TorstenJahnke** [kvic-z/pixelserv-tls#5]
Hi!

Is it possible to add a switch which disable the entire logging and statistic website?

**Comment by kvic-z** [comment]
Pls check out '-l 0' which is near nothing other than the first few lines on startup that tells what ports pixelserv-tls listen.

**Comment by TorstenJahnke** [comment]
Thanks a lot!!! It's running and I need one more day for more.
Keep you informed...

**Comment by kvic-z** [comment]
I plan to add an "admin" port where, if specified from command line, pixelserv-tls will only answer to admin commands such as "log" and "servstats". With this "admin" port, users can easily filter who can access e.g. through iptables. 

Any thought?

**Comment by TorstenJahnke** [comment]
As long as you keep the option to disable this logging alive I'm fine with it.
For debugging and testing it's a real usefull feature. Great idea :)

**Comment by kvic-z** [comment]
A new feature "admin" port is added in this [commit](https://github.com/kvic-z/pixelserv-tls/commit/cee0e52ba38b8f11383be82cc24c89c68aed84ed) :)

**Comment by decoderman** [comment]
-A just sets the port to a set number, but there's no authentication, even if set.
Is that to obscure it? A port sniffer would still pick it up I guess.

**Comment by TorstenJahnke** [comment]
Disable Port Scan can be done with IP Tables:

IPTABLES -A INPUT -p tcp --tcp-flags SYN,ACK SYN,ACK -m state --state NEW -j DROP
IPTABLES -A INPUT -p tcp --tcp-flags ALL NONE -j DROP

IPTABLES -A INPUT -p tcp --tcp-flags SYN,FIN SYN,FIN -j DROP
IPTABLES -A INPUT -p tcp --tcp-flags SYN,RST SYN,RST -j DROP
IPTABLES -A INPUT -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j DROP

IPTABLES -A INPUT -p tcp --tcp-flags FIN,RST FIN,RST -j DROP
IPTABLES -A INPUT -p tcp --tcp-flags ACK,FIN FIN -j DROP
IPTABLES -A INPUT -p tcp --tcp-flags ACK,PSH PSH -j DROP
IPTABLES -A INPUT -p tcp --tcp-flags ACK,URG URG -j DROP
