### ISSUE TITLE
Does not compile on Debian Stretch with libssl-dev:amd64 1.1.0f-3+deb9u1 - WORKAROUND

### ISSUE THREAD

**Issue by emeidi** [kvic-z/pixelserv-tls#6]
Error message when compiling:

```
configure:3567: gcc -o conftest -g -O2   conftest.c -lssl  -lcrypto  >&5
/tmp/cccBprK6.o: In function `main':
/usr/local/apps/pixelserv/src-new/conftest.c:23: undefined reference to `SSL_library_init'
collect2: error: ld returned 1 exit status
```

Adjust configure.ac — replace "SSL_library_init" with "SSL_CTX_new":

```
...
 8 AC_CHECK_LIB([ssl], [SSL_CTX_new], [],
 9         AC_MSG_FAILURE([can't find openssl ssl lib]))
...
```

As described here:

https://github.com/allinurl/goaccess/issues/591
https://github.com/allinurl/goaccess/pull/771
https://github.com/allinurl/goaccess/pull/771/commits/4152916ca78f3fddf418ecc833f0c91050bbb4a2

**Comment by kvic-z** [comment]
Thanks!

Added your fix in [428d2f](https://github.com/kvic-z/pixelserv-tls/commit/428d2fad1e89e595c9e3d5ecb8d2c52353315e07)
