### ISSUE TITLE
Crash on request to `https://localhost`

### ISSUE THREAD

**Issue by liljaylj** [kvic-z/pixelserv-tls#9]
If I run `pixelserv-tls` with following command `sudo -u root pixelserv-tls -z /var/cache/pixelserv -l 5 -f` it crashes on request to `https://localhost` with following message:
```
pixelserv-tls[7413]: pixelserv-tls: v2.0.1 compiled: Jan 20 2018 00:17:28 options: -z /var/cache/pixelserv -l 5 -f
pixelserv-tls[7413]: Listening on :*:80
pixelserv-tls[7413]: Listening on :*:443
zsh: segmentation fault  sudo -u root pixelserv-tls -z /var/cache/pixelserv -l 5 -f
```

**Comment by kvic-z** [comment]
Thanks for reporting the issue. Fixed in [34163f1](https://github.com/kvic-z/pixelserv-tls/commit/34163f114c8df302211fc76f9c38a96b9806e8cc).
